/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mytailor;

/**
 *
 * @author aalib
 */
public class HOME extends javax.swing.JFrame {

    /**
     * Creates new form HOME
     */
    public HOME() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        AddStuff = new javax.swing.JButton();
        orderview = new javax.swing.JButton();
        Viiewuser = new javax.swing.JButton();
        BILL = new javax.swing.JButton();
        Adduser = new javax.swing.JButton();
        Orderview = new javax.swing.JButton();
        AddOrder = new javax.swing.JButton();
        AddStaff = new javax.swing.JButton();
        Assing = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Transection = new javax.swing.JButton();
        Logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 204));
        setFont(new java.awt.Font("OCR A Extended", 1, 18)); // NOI18N
        setForeground(new java.awt.Color(204, 204, 204));

        jLabel1.setBackground(new java.awt.Color(255, 204, 204));
        jLabel1.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 48)); // NOI18N
        jLabel1.setText("Mnagement");
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 204, 204), new java.awt.Color(255, 204, 204), null, null));

        AddStuff.setBackground(new java.awt.Color(255, 204, 204));
        AddStuff.setFont(new java.awt.Font("OCR A Extended", 1, 18)); // NOI18N
        AddStuff.setForeground(new java.awt.Color(102, 102, 102));
        AddStuff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fashion/designing/system/image/addmaterial.png"))); // NOI18N
        AddStuff.setText("Add stuf");
        AddStuff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddStuffActionPerformed(evt);
            }
        });

        orderview.setBackground(new java.awt.Color(255, 204, 204));
        orderview.setFont(new java.awt.Font("OCR A Extended", 1, 18)); // NOI18N
        orderview.setForeground(new java.awt.Color(102, 102, 102));
        orderview.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fashion/designing/system/image/ICO (5).png"))); // NOI18N
        orderview.setText("Staaff pay");
        orderview.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        orderview.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        orderview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderviewActionPerformed(evt);
            }
        });

        Viiewuser.setBackground(new java.awt.Color(255, 204, 204));
        Viiewuser.setFont(new java.awt.Font("OCR A Extended", 1, 18)); // NOI18N
        Viiewuser.setForeground(new java.awt.Color(102, 102, 102));
        Viiewuser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fashion/designing/system/image/ICO (4).png"))); // NOI18N
        Viiewuser.setText("View User info");
        Viiewuser.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Viiewuser.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        Viiewuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViiewuserActionPerformed(evt);
            }
        });

        BILL.setBackground(new java.awt.Color(255, 204, 204));
        BILL.setFont(new java.awt.Font("OCR A Extended", 1, 18)); // NOI18N
        BILL.setForeground(new java.awt.Color(102, 102, 102));
        BILL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fashion/designing/system/image/ICO (5).png"))); // NOI18N
        BILL.setText("Customer Bill");
        BILL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BILLActionPerformed(evt);
            }
        });

        Adduser.setBackground(new java.awt.Color(255, 204, 204));
        Adduser.setFont(new java.awt.Font("OCR A Extended", 1, 18)); // NOI18N
        Adduser.setForeground(new java.awt.Color(102, 102, 102));
        Adduser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fashion/designing/system/image/addlogin.png"))); // NOI18N
        Adduser.setText("Add user");
        Adduser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdduserActionPerformed(evt);
            }
        });

        Orderview.setBackground(new java.awt.Color(255, 204, 204));
        Orderview.setFont(new java.awt.Font("OCR A Extended", 1, 18)); // NOI18N
        Orderview.setForeground(new java.awt.Color(102, 102, 102));
        Orderview.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fashion/designing/system/image/ICO (9).png"))); // NOI18N
        Orderview.setText("Oredre Details");
        Orderview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderviewActionPerformed(evt);
            }
        });

        AddOrder.setBackground(new java.awt.Color(255, 204, 204));
        AddOrder.setFont(new java.awt.Font("OCR A Extended", 1, 18)); // NOI18N
        AddOrder.setForeground(new java.awt.Color(102, 102, 102));
        AddOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fashion/designing/system/image/StaffIcon.png"))); // NOI18N
        AddOrder.setText("Add customer");
        AddOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddOrderActionPerformed(evt);
            }
        });

        AddStaff.setBackground(new java.awt.Color(255, 204, 204));
        AddStaff.setFont(new java.awt.Font("OCR A Extended", 1, 18)); // NOI18N
        AddStaff.setForeground(new java.awt.Color(102, 102, 102));
        AddStaff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fashion/designing/system/image/Staff Prfile.png"))); // NOI18N
        AddStaff.setText("Add staff");
        AddStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddStaffActionPerformed(evt);
            }
        });

        Assing.setBackground(new java.awt.Color(255, 204, 204));
        Assing.setFont(new java.awt.Font("OCR A Extended", 1, 18)); // NOI18N
        Assing.setForeground(new java.awt.Color(102, 102, 102));
        Assing.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fashion/designing/system/image/OrdertIcon.png"))); // NOI18N
        Assing.setText("Assing oredr");
        Assing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AssingActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(102, 102, 102));
        jLabel2.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 48)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fashion/designing/system/image/Sewing-Machine.png"))); // NOI18N
        jLabel2.setText("My Tailor Admin");
        jLabel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 204, 204), new java.awt.Color(255, 204, 204), null, null));

        jLabel3.setBackground(new java.awt.Color(102, 102, 102));
        jLabel3.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 48)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fashion/designing/system/image/CustomerDetailIcon.png"))); // NOI18N
        jLabel3.setText("Customer");
        jLabel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 204, 204), new java.awt.Color(255, 204, 204), null, null));

        jLabel4.setBackground(new java.awt.Color(102, 102, 102));
        jLabel4.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 48)); // NOI18N
        jLabel4.setText("Staf ");
        jLabel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 204, 204), new java.awt.Color(255, 204, 204), null, null));

        Transection.setBackground(new java.awt.Color(255, 204, 204));
        Transection.setFont(new java.awt.Font("OCR A Extended", 1, 18)); // NOI18N
        Transection.setForeground(new java.awt.Color(102, 102, 102));
        Transection.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fashion/designing/system/image/ICO (5).png"))); // NOI18N
        Transection.setText("Transection info");
        Transection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransectionActionPerformed(evt);
            }
        });

        Logout.setBackground(new java.awt.Color(255, 204, 204));
        Logout.setFont(new java.awt.Font("OCR A Extended", 1, 18)); // NOI18N
        Logout.setForeground(new java.awt.Color(102, 102, 102));
        Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fashion/designing/system/image/ic_exit_group.png"))); // NOI18N
        Logout.setText("Logout");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(Viiewuser, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(orderview, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(Orderview, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(AddOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(Assing, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(AddStuff, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(BILL, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(AddStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(Adduser, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(Transection, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(168, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Viiewuser)
                    .addComponent(orderview, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Orderview, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Assing, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(AddStuff, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BILL, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Adduser, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Transection, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AdduserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdduserActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_AdduserActionPerformed

    private void AddOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddOrderActionPerformed
        // TODO add your handling code here:
        customer_info cm=new customer_info();
        cm.setVisible(true);
            dispose();
    }//GEN-LAST:event_AddOrderActionPerformed

    private void AddStuffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddStuffActionPerformed
        // TODO add your handling code here:
        MaterialExpense stf=new MaterialExpense();
        stf.setVisible(true);
            dispose();
    }//GEN-LAST:event_AddStuffActionPerformed

    private void AddStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddStaffActionPerformed
        // TODO add your handling code here:
        StaffInfo st=new StaffInfo();
        st.setVisible(true);
            dispose();
    }//GEN-LAST:event_AddStaffActionPerformed

    private void ViiewuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViiewuserActionPerformed
        // TODO add your handling code here:
        CustomerView cm=new CustomerView();
        cm.setVisible(true);
            dispose();
    }//GEN-LAST:event_ViiewuserActionPerformed

    private void orderviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderviewActionPerformed
        // TODO add your handling code here:
        AddStaffPayment od=new AddStaffPayment();
        od.setVisible(true);
            dispose();
    }//GEN-LAST:event_orderviewActionPerformed

    private void AssingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AssingActionPerformed
        // TODO add your handling code here:
        AssignmentForm as=new AssignmentForm();
        as.setVisible(true);
            dispose();
    }//GEN-LAST:event_AssingActionPerformed

    private void BILLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BILLActionPerformed
        // TODO add your handling code here:
        Payment pm=new Payment();
        pm.setVisible(true);
            dispose();
    }//GEN-LAST:event_BILLActionPerformed

    private void OrderviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderviewActionPerformed
        // TODO add your handling code here:
        OrderView od=new OrderView();
        od.setVisible(true);
            dispose();
    }//GEN-LAST:event_OrderviewActionPerformed

    private void TransectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransectionActionPerformed
        // TODO add your handling code here:
        StaffSalray tz=new StaffSalray();
        tz.setVisible(true);
            dispose();
    }//GEN-LAST:event_TransectionActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        // TODO add your handling code here:
        Login lg=new Login();
        lg.setVisible(true);
            dispose();
    }//GEN-LAST:event_LogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HOME().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddOrder;
    private javax.swing.JButton AddStaff;
    private javax.swing.JButton AddStuff;
    private javax.swing.JButton Adduser;
    private javax.swing.JButton Assing;
    private javax.swing.JButton BILL;
    private javax.swing.JButton Logout;
    private javax.swing.JButton Orderview;
    private javax.swing.JButton Transection;
    private javax.swing.JButton Viiewuser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton orderview;
    // End of variables declaration//GEN-END:variables
}
